// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhtuSm_LNmBmbO_dYPU5fMX8VVImv1bWY',
    appId: '1:417227106160:web:16be9fe6aeba3ca00c51b5',
    messagingSenderId: '417227106160',
    projectId: 'neurorite-23160',
    authDomain: 'neurorite-23160.firebaseapp.com',
    storageBucket: 'neurorite-23160.appspot.com',
    measurementId: 'G-Q7B01VHWR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQnw1F9cdC2TDlkf9eTrcmNTqMwMY7NQE',
    appId: '1:417227106160:android:fb10f6233e1366520c51b5',
    messagingSenderId: '417227106160',
    projectId: 'neurorite-23160',
    storageBucket: 'neurorite-23160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnflDs14c7IDevxK6rlIix3DgH0gOiXrU',
    appId: '1:417227106160:ios:e085199f8629fb100c51b5',
    messagingSenderId: '417227106160',
    projectId: 'neurorite-23160',
    storageBucket: 'neurorite-23160.appspot.com',
    iosBundleId: 'dev.hau.neurorite',
  );
}
